// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillUp.Models;

#nullable disable

namespace SkillUp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230505003637_mymig")]
    partial class mymig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CandidatTraining", b =>
                {
                    b.Property<long>("candidatsId")
                        .HasColumnType("bigint");

                    b.Property<int>("trainingsId")
                        .HasColumnType("integer");

                    b.HasKey("candidatsId", "trainingsId");

                    b.HasIndex("trainingsId");

                    b.ToTable("CandidatTraining");
                });

            modelBuilder.Entity("SkillUp.Models.Candidat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dateNaissance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fonction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("candidats");
                });

            modelBuilder.Entity("SkillUp.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("trainingcenterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("trainingcenterId");

                    b.ToTable("trainings");
                });

            modelBuilder.Entity("SkillUp.Models.TrainingCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("trainingCenters");
                });

            modelBuilder.Entity("SkillUp.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mdp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CandidatTraining", b =>
                {
                    b.HasOne("SkillUp.Models.Candidat", null)
                        .WithMany()
                        .HasForeignKey("candidatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUp.Models.Training", null)
                        .WithMany()
                        .HasForeignKey("trainingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillUp.Models.Training", b =>
                {
                    b.HasOne("SkillUp.Models.TrainingCenter", "trainingcenter")
                        .WithMany("trainings")
                        .HasForeignKey("trainingcenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trainingcenter");
                });

            modelBuilder.Entity("SkillUp.Models.TrainingCenter", b =>
                {
                    b.Navigation("trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
